In [4]:
import numpy as np 
import random 
import itertools 

In [8]:
def step(x):
    return 1 if x >= 0 else 0

In [18]:
def forward_propagate(X, w1, b1, w2, b2): 
    
    z1 = np.dot(X, w1) + b1 
    a1 = np.vectorize(step) (z1) 
    z2 = np.dot(a1, w2) + b2 
    a2 = np.vectorize(step) (z2) 
    
    return a2

In [12]:
def generate_combinations(n):
    return np.array(list(itertools.product([0, 1], repeat=n)))

In [43]:
num_inputs = 2
X = generate_combinations(num_inputs)

output = []
for row in X:
    temp = []
    print(f"Enter the output for the inputs {list(row)}")
    a = int(input("1. "))
    b = int(input("2. "))
    temp.append(a)
    temp.append(b)
    output.append(temp)
y = np.array(output)
print(y)

Enter the output for the inputs [0, 0]


1.  1
2.  0


Enter the output for the inputs [0, 1]


1.  1
2.  1


Enter the output for the inputs [1, 0]


1.  0
2.  1


Enter the output for the inputs [1, 1]


1.  0
2.  1


[[1 0]
 [1 1]
 [0 1]
 [0 1]]


In [51]:
found = False 
iterations = 0

while not found: 
    iterations += 1
    w1 = np.random.uniform(-2, 2, (num_inputs, 3))
    b1 = np.random.randint(-3, 3)

    w2 = np.random.uniform(-2, 2, (3, 2))
    b2 = np.random.randint(-3, 3)

    result = forward_propagate(X, w1, b1, w2, b2)
    if np.array_equal(np.array(result), y):
        print(f"Found at iteration: {iterations}")
        print(w1)
        print(b1)
        print(w2)
        print(b2)
        found = True

    if iterations % 100000 == 0:
        print(f"Iteration {iterations}: still searching...")

Found at iteration: 9357
[[ 0.16160028 -1.13464554 -1.93723633]
 [ 0.18000064 -0.33339169  1.66908886]]
0
[[-1.37754866  1.25892256]
 [ 1.32376206 -1.57107001]
 [ 1.76017669 -1.08694303]]
0
